language: ruby
rvm:
- 2.1
cache:
- bundler
gemfile: travisGemfile
install:
- bundle install
before_script:
- chmod +x deploy.sh
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script: "./deploy.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - HTML_FOLDER="./_site/"
  - GH_REF="nandomoreirame/dotX"
branches:
  only:
  - master
  - source
notifications:
  email: false
